#!/bin/bash
# PITCH DAY -- ButtsCorp
# Run this before walking into each target
# Usage: bash pitch_day.sh [rcb|chew|countryside|caseys|baymont]

TARGET=$1
BASE="/storage/emulated/0/RootBase/Official-Vertical-AI-Boardroom"

echo ""
echo "============================================"
echo "  BUTTSCORP PITCH PREP"
echo "  Target: $TARGET"
echo "============================================"
echo ""

case $TARGET in

  rcb)
    echo "TARGET: RCB BANK"
    echo "Address: East 16th Street, Wellington KS"
    echo "Rating: 3.4 stars / 5 reviews"
    echo "Decision maker: Branch manager"
    echo ""
    echo "OPENING LINE:"
    echo "  'I noticed RCB Bank has 3.4 stars and only 5 Google"
    echo "   reviews. That's not a service problem -- that's a"
    echo "   visibility problem. I built something that fixes it."
    echo "   Takes 15 minutes to show you.'"
    echo ""
    echo "IF FRONT DESK STOPS YOU:"
    echo "  'I have a short business proposal for your manager."
    echo "   It's specifically about your Google presence."
    echo "   I only need 15 minutes.'"
    echo ""
    echo "PRODUCT: Digital Trust Builder"
    echo "PRICE: \$299/month"
    echo "GUARANTEE: 25 more Google reviews in 90 days or free"
    echo ""
    echo "OBJECTIONS:"
    echo "  No budget: 'The guarantee means you pay nothing if"
    echo "              it doesn't work. Zero risk.'"
    echo "  Not interested: 'Chase is deploying AI across 4,800"
    echo "                   branches right now. You have 18 months"
    echo "                   before your small business customers"
    echo "                   notice. I can show you how to compete.'"
    echo "  Already have someone: 'What are they doing about your"
    echo "                         3.4 star rating specifically?'"
    echo ""
    cat $BASE/reports/RCB_Bank_pitch.txt
    ;;

  chew)
    echo "TARGET: CHEW PLUMBING"
    echo "Address: Wellington KS"
    echo "Rating: 4.3 stars / 42 reviews / NO WEBSITE"
    echo "Decision maker: Owner"
    echo ""
    echo "FRONT DESK SITUATION:"
    echo "  If there's a front desk person listening --"
    echo "  DO NOT pitch around her. Pitch TO her first."
    echo "  'You're clearly the one holding this place together."
    echo "   What I built would make YOUR life easier, not harder."
    echo "   You'd stop getting calls from people who just want"
    echo "   a price and never book. Yvette filters them for you.'"
    echo ""
    echo "OPENING LINE TO OWNER:"
    echo "  'Your reviews say you do good work. Your backlog says"
    echo "   you have more demand than capacity. The gap is intake."
    echo "   I built an AI dispatcher named Yvette that fixes that.'"
    echo ""
    echo "PRODUCT: Yvette AI Intake System"
    echo "PRICE: \$249/month"
    echo "DEMO: Ask them their 3 most common call types."
    echo "      Show how Yvette handles each one on your phone."
    echo ""
    echo "YVETTE DEMO SCRIPT:"
    echo "  'Customer calls: my heat is out.'"
    echo "  Yvette asks: Is there a light blinking in the furnace window?"
    echo "  Customer: yes, 4 times"
    echo "  Yvette: That's a high limit fault. Check your filter first."
    echo "          I'll have a tech call you in 20 minutes with parts."
    echo "  Owner reaction: that just saved a truck roll."
    echo ""
    echo "OBJECTIONS:"
    echo "  We answer our own phones: 'Yvette works after hours,"
    echo "    weekends, and when you're on a job. She never misses"
    echo "    a call.'"
    echo "  Too expensive: 'One saved truck roll pays for two months.'"
    echo ""
    cat $BASE/reports/Chew_Plumbing_pitch.txt
    ;;

  countryside)
    echo "TARGET: COUNTRYSIDE MOTORS"
    echo "Address: Wellington KS"
    echo "Rating: 4.7 stars / 331 reviews"
    echo "Decision maker: Chris Jesina / Rich Jesina"
    echo ""
    echo "NOTE: 4.7 stars means they're WINNING."
    echo "Don't pitch repair. Pitch growth and protection."
    echo ""
    echo "FRONT DESK / LOT APPROACH:"
    echo "  Walk the lot first. Look at the surface."
    echo "  If it's as bad as you say, that's your opener."
    echo "  'That lot is costing you sales. Customers judge"
    echo "   the dealership by the lot before they judge the cars.'"
    echo ""
    echo "TWO PITCH OPTIONS:"
    echo ""
    echo "  OPTION A -- Rural Revive (with Luke):"
    echo "  'I have a crew ready to seal coat and stripe this lot."
    echo "   First job is free if you put us in touch with your"
    echo "   other commercial contacts in the area.'"
    echo ""
    echo "  OPTION B -- AutoPilot AI:"
    echo "  'You have 331 reviews and 4.7 stars. You built that"
    echo "   on honesty and no pressure. AutoPilot qualifies your"
    echo "   leads before they walk in so you only spend time on"
    echo "   serious buyers. Protects what you built.'"
    echo ""
    echo "  OPTION C -- The trade:"
    echo "  'I'll build you a 90-day AI lead system pilot."
    echo "   Take it out in trade on that [point at something"
    echo "   on the lot]. You get the system, I get mobile.'"
    echo ""
    echo "PRICE: \$299/month OR vehicle trade"
    echo ""
    cat $BASE/reports/Countryside_Motors_pitch.txt
    ;;

  caseys)
    echo "TARGET: CASEY'S GENERAL STORE"
    echo "Address: Wellington KS"
    echo "Contact: Tyler Christians (you have his number)"
    echo ""
    echo "NOTE: Don't cold walk this one."
    echo "Text Tyler first: 'Hey Tyler -- Mike."
    echo "Got the CaseyOS breakdown ready."
    echo "Got 10 min this week to look at it?'"
    echo ""
    echo "PRODUCT: CaseyOS"
    echo "PRICE: \$199/month"
    echo ""
    echo "PITCH ANGLE:"
    echo "  Not selling software to Casey's corporate."
    echo "  Selling Tyler Christians his own store."
    echo "  'This makes you the top performer in your district."
    echo "   That's how you get offered a franchise.'"
    echo ""
    echo "KEY PAIN POINTS TO HIT:"
    echo "  - Lotto counts taking too long"
    echo "  - Tobacco inventory shrink"
    echo "  - Truck orders based on gut feel"
    echo "  - Books eating 2 hours every night"
    echo ""
    cat $BASE/reports/CaseyOS_pitch.txt
    ;;

  baymont)
    echo "TARGET: BAYMONT / PENNY'S HOTEL GROUP"
    echo "Address: Wellington KS (North Washington)"
    echo "Owner: Likely Patel family (Kaushik Patel -- KS SOS)"
    echo "Decision maker: Owner, NOT Karen the manager"
    echo ""
    echo "APPROACH:"
    echo "  Do NOT pitch Karen. She's the problem, not the solution."
    echo "  Ask for the owner by name if possible."
    echo "  If Patel: 'I'd like to speak with Mr. Patel about"
    echo "             a proposal for the property management.'"
    echo ""
    echo "OPENING LINE:"
    echo "  'You're running three properties with one management"
    echo "   layer and a BNSF contract. I built a system that"
    echo "   coordinates all three without adding staff.'"
    echo ""
    echo "PAIN POINTS:"
    echo "  - North property unstaffed, no accountability"
    echo "  - Lost and found theft ongoing"
    echo "  - BNSF booking coordination manual"
    echo "  - Overnight staff unreliable"
    echo ""
    echo "PRODUCT: HospitalityOS"
    echo "PRICE: \$499-999/month (they have budget)"
    echo ""
    echo "WATCH OUT:"
    echo "  Don't mention what you know about the theft or"
    echo "  the overnight staff situation directly."
    echo "  Frame it as: 'Properties this size typically lose"
    echo "  15-20% of lost and found inventory without a"
    echo "  tracking system. I can fix that.'"
    echo ""
    ;;

  *)
    echo "Usage: bash pitch_day.sh [rcb|chew|countryside|caseys|baymont]"
    echo ""
    echo "Available targets:"
    echo "  rcb        -- RCB Bank"
    echo "  chew       -- Chew Plumbing (Yvette)"
    echo "  countryside -- Countryside Motors (AutoPilot/Rural Revive)"
    echo "  caseys     -- Casey's General Store (CaseyOS/Tyler)"
    echo "  baymont    -- Penny's/Baymont Hotel Group"
    ;;
esac

echo ""
echo "============================================"
echo "  REMEMBER:"
echo "  You built this. You know what it does."
echo "  They need it more than you need them."
echo "  One yes is all it takes."
echo "============================================"
echo ""
